// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutostarterEnabled() {
  return window['go']['main']['App']['GetAutostarterEnabled']();
}

export function GetKeys() {
  return window['go']['main']['App']['GetKeys']();
}

export function GetModifiers() {
  return window['go']['main']['App']['GetModifiers']();
}

export function SetAutostarterEnabled(arg1) {
  return window['go']['main']['App']['SetAutostarterEnabled'](arg1);
}

export function SetToggleHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetToggleHotkey'](arg1, arg2);
}

export function SetWindowBounds(arg1) {
  return window['go']['main']['App']['SetWindowBounds'](arg1);
}
