// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hotkey} from '../models';

export function GetKeys():Promise<{[key: string]: hotkey.Key}>;

export function GetModifiers():Promise<{[key: string]: hotkey.Modifier}>;

export function Greet(arg1:string):Promise<string>;

export function SetToggleHotkey(arg1:Array<hotkey.Modifier>,arg2:hotkey.Key):Promise<void>;
